# Generated by Django 4.1.5 on 2023-01-19 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=0, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='change_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='product',
            name='create_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=0, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, verbose_name='Имя категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_product',
            field=models.CharField(max_length=250, verbose_name='Имя'),
        ),
    ]
